public class Removeduplicate {
    public static void MyList(){
        List<String> names = new List<String>{'A','B','A','C'};
            set<string> myset=new set<string>();
        myset.addAll(names);
        system.debug(myset);
        names.add(3,'d');
        system.debug(names);
        
        map<integer,string> MyMap=new map<integer,string>();
        MyMap.put(1,'sojab');
        system.debug(MyMap);
    }
}